"""create review_time column

Revision ID: cfb6e7ccec5c
Revises: e11a358c9834
Create Date: 2026-09-13 12:09:47.311687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb6e7ccec5c'
down_revision: Union[str, Sequence[str], None] = 'e11a358c9834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('review_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'review_time')
    # ### end Alembic commands ###
